//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudCluster) DeepCopyInto(out *HuaweiCloudCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudCluster.
func (in *HuaweiCloudCluster) DeepCopy() *HuaweiCloudCluster {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HuaweiCloudCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudClusterList) DeepCopyInto(out *HuaweiCloudClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HuaweiCloudCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudClusterList.
func (in *HuaweiCloudClusterList) DeepCopy() *HuaweiCloudClusterList {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HuaweiCloudClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudClusterSpec) DeepCopyInto(out *HuaweiCloudClusterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudClusterSpec.
func (in *HuaweiCloudClusterSpec) DeepCopy() *HuaweiCloudClusterSpec {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudClusterStatus) DeepCopyInto(out *HuaweiCloudClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudClusterStatus.
func (in *HuaweiCloudClusterStatus) DeepCopy() *HuaweiCloudClusterStatus {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachine) DeepCopyInto(out *HuaweiCloudMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachine.
func (in *HuaweiCloudMachine) DeepCopy() *HuaweiCloudMachine {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HuaweiCloudMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachineList) DeepCopyInto(out *HuaweiCloudMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HuaweiCloudMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachineList.
func (in *HuaweiCloudMachineList) DeepCopy() *HuaweiCloudMachineList {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HuaweiCloudMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachineSpec) DeepCopyInto(out *HuaweiCloudMachineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachineSpec.
func (in *HuaweiCloudMachineSpec) DeepCopy() *HuaweiCloudMachineSpec {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachineStatus) DeepCopyInto(out *HuaweiCloudMachineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachineStatus.
func (in *HuaweiCloudMachineStatus) DeepCopy() *HuaweiCloudMachineStatus {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachineTemplate) DeepCopyInto(out *HuaweiCloudMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachineTemplate.
func (in *HuaweiCloudMachineTemplate) DeepCopy() *HuaweiCloudMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HuaweiCloudMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachineTemplateList) DeepCopyInto(out *HuaweiCloudMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HuaweiCloudMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachineTemplateList.
func (in *HuaweiCloudMachineTemplateList) DeepCopy() *HuaweiCloudMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HuaweiCloudMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachineTemplateSpec) DeepCopyInto(out *HuaweiCloudMachineTemplateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachineTemplateSpec.
func (in *HuaweiCloudMachineTemplateSpec) DeepCopy() *HuaweiCloudMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HuaweiCloudMachineTemplateStatus) DeepCopyInto(out *HuaweiCloudMachineTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HuaweiCloudMachineTemplateStatus.
func (in *HuaweiCloudMachineTemplateStatus) DeepCopy() *HuaweiCloudMachineTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(HuaweiCloudMachineTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
